[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sonu Thapa", email = "37073011+mesailesh7@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[tool.uv]
package = false
